repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.12.0
    hooks:
      - id: pyupgrade
        args:
          - --py36-plus
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
        name: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^test/test_po2md/translate-examples/markuptext/code-blocks\.md\.expect\.md
        name: end-of-file-fixer
      - id: double-quote-string-fixer
        name: double-quote-string-fixer
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
      - id: add-trailing-comma
        name: add-trailing-comma
        args:
          - --py36-plus
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.17.0
    hooks:
      - id: setup-cfg-fmt
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
        name: flake8-package
        additional_dependencies:
          - flake8-print
          - flake8-implicit-str-concat
          - flake8-docstrings
        files: ^mdpo/
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
        name: flake8-tests
        additional_dependencies:
          - flake8-print
          - flake8-implicit-str-concat
        files: ^test/
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
        name: flake8-docs
        additional_dependencies:
          - flake8-print
          - flake8-implicit-str-concat
        files: ^docs/
  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort
        args:
          - --filter-files
        files: \.py$
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.1
    hooks:
      - id: yamllint
        files: .+\.(yml|yaml)
        args:
          - -c
          - .yamllint
